version: "3.7"

services:

  #PHP Service
  app:
    build: ./docker/php/
    # image: php
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #PostgreSQL Service
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: postgres
    container_name: db
    volumes:
      - ./docker/mt-postgres.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
